#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

wx = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAB61J"
    "REFUWIW9l1tsW3cdxz/HPj52HMc+dhInzT3pellSygJ0W9eytbuwl65Q9oA0CaiEhFQe4A3o"
    "LghtaEiIisEEFRUSSIVpVFRd2VatQLe2VKKlpW0CzaXNrXFi0sSxz7GP7XN8OYeH4zhx7PWB"
    "h/1e/P//rt/zu/z/fwvTZ05bAGDySVLy2hD+X72BmJ++i/XWWwBEX/9xhVLbi4e5dfAQwS1d"
    "NsO6v9O2Fw9X+VgvUw0VgOtuPzeTJqJp5HBPjpHz+FB1lZYTp/GMj3P3le/SMznGwO+Ocuvg"
    "ITZcPk9yQzdmwE/fOycAGP3B92k5cZrQ1SuM/vR1eibHkF96CQB9yxZCY6NlvZ7JMVRdpfu1"
    "nwDw4Y7HAHCsIJR0DffwFK3vn0KeGKHt5LsAqAMDDL7yHTzj42z+zRtk5UakyTHiWx/k2mVb"
    "P/XkU7T9ydZf3PMF5IkRQmOjSJNjSJNjIKxmQp4YQZ4YKe/LAJQH+jG29d43xUv7n8fR4Qeg"
    "9f1TZf7w4DNo+/YBYAb81YbrSre0//lVAIamAeC1zPuW2GvZTXrqH3KZ92+lD4C93/saf/yX"
    "UNOugkoqzX8+ucoaevWHVvyJJ1B1Fcu01uqVAQkOm/PbMxZCXWBVKEBAsmVqziIgCezpTxIM"
    "WtVOVhyX9h9+cImZXx9DXMjB0M07aLqGoxTILAFxOAR8XpmZiSlkOUjiyhnkwa/i8HeuIEPN"
    "Q8BlgQWqYXF+xC7B9rZZUqn4xyZjbt6Wia0SRMPN1BtN1AkiglQkY1gYhQzB+noAZgBFSbB9"
    "506Ewg1mVAtnqAeAgGiDDbgFVMNCNVY/ubuzh9U2qzxnIlPTLK2RUieIKPkkiXQar1tAdvlZ"
    "jitcHhOIzs8zm5CQ5SCW2EAwfQl5/vfl4CsUcAvgtF3+fbqT8yMyWcOsCg5QL4l2lldqI0jF"
    "CoVENsGdxSD5ooi8+cv4PRCNziDLQfq2D+ALbSDyz5/hNNOVIESrDEI1LK5Mymu/s4psiQWJ"
    "dBrZ5Ud2+blx2+DCECwkYTlbJF7w4gzvxnSFiUZnME2Lzz7yOXbv3YN17yy3zr5RdqgWKqdB"
    "1Vf6ojYIcWXhFr0ALMbnUYtbESTFFhRMkByoBQiEduESVCIT54gvJAi1Bqn3yWx/SAAzTdFh"
    "9wxFE0tXGT33Jv76BoqDB1hqzNHc0lyenioARiHD1ZszJJwDgGIrlqYC07TrC+hWAGfLsyix"
    "G2SmZujo6yFEkLmpvxBfTuHo/hIUTEY+eI3ux75JndtDZvIkY1Yvpvkg/lArde71JQD+GzWI"
    "F0vjtdJbBRNKI6kaFmpBQC0IFB31OMO7iRnNzE3NIDeG+fzevYSbG0iOv8PouTfpfOTruEQX"
    "AAdeOIiS0AiH2qmTapQgrZvcVpsQpNpXslVI2YucDUYpZcbRugvEDDPzGuOmQMz7FA2dCq2x"
    "4zTIXaQS0zy9qxFBEHjuwHNAscq3GFV1zg6/h+DrQ/Bvs7nrT7FCCdhKSUr71J0/kMwtASD7"
    "mzBTcVwNIdwbn2TiyklECgSffgGAjFEonzNYoOkFG4ClJdF0ELSr+ADL01kzC+tJm7tAJhbF"
    "J+QIdPaST8VZTGTxhx5gcWIYEWjyp9GKOg7BaWeukESm8rISAXo2+LgbWUZbuIolTiEEP4Wj"
    "NBUu0UW+kC+vDcO+vFaCA6iRaRx9z+APwd1b16hzSzz8aD8be5rJZdMIpXNBEJ0ksgk7uaXe"
    "Eh16GgsXXS1hZu8tkolF8QJCYBNFZz1G0SijNYoGc9dP097Tgy/cgZVbIq0YeJvaiE0MkzVy"
    "uNxeujpdtHc0IEoeCjndDiR5AMhnMzaAXNbmm556IsP2y6Vr80Yc3V5uDY3jjkVwNnUiBjZR"
    "dHhwmjp3h/5mt8LyNKrpJ2mIdA88SnRihLxhZ+Ph7UHaO+x3hZZRyuDNXLZ82QEks+ZqBszG"
    "XoqxWZYXY7gEgbdnrthaM9cq6pXz+Djcv4P5eAZVidCx6SHCf/0lxxxrjuN3K3slF25jenAH"
    "l/o+zdoXRz4VRwAc+BsJmgkCQR+/uHGeI9c/qnDwI6GhvJZ0jSPXPyLc2IAk9zM/p5Do3sr9"
    "SFqMsuXsab5x9FXU2CyKkiCpRMtyB0DHpl5cQu0XzX+6+6t4O8aHyBsZrEK6hgWc39DL+LNf"
    "rOJ/5tIFsrqKlsmRLr2wRDOnoyHib27k24N7UBMaC5qJlVd4PLnEV5JzVY6OS2HI3QPA0xyG"
    "SDWIY0tJjtQAV8zYTVhQ7F8RQElo5E0LV0OIALCgJcFZx8tWCuKpCgc5jw+KWQSXzLb+HtAS"
    "NbPwcZTMmuRNCwNnCYCRJZ9KkLZMpLg9431eaI/M8rJZz0WXyMWiWnYg6RrvAYd6O1CSMTzJ"
    "bFUQvVhEV7SafCUZAyCeWKIFEB2WSdoyEdQUR2dvVFo44HECVY4kXUNQ7cyYxdq9Yxaqz32g"
    "bLcmhM2cjat2etdRXXBjFS/n8RFJCWiWRHvkTpU8Wyjy88XbVfylTLZsp2vLqwA0y74j97nD"
    "VUZnY9erePvcYay8QjyxVOMb4UB8HkmvLsFxZ0OVnfCtji7rpJasUt5ZENjctPonZFrRuEi+"
    "ZsD/lzbrKYT9Xr+VMGvP8ydB/wNzNW0SdDi3xwAAAABJRU5ErkJggg==")
getwxData = wx.GetData
getwxImage = wx.GetImage
getwxBitmap = wx.GetBitmap

